baseURL = "https://sigon-lang.github.io/docs/"
languageCode = "en-us"
title = "Sigon Lang"
theme = "hyde-y"
publishDir = "docs"

# For search functionnality
[outputs]
home = [ "HTML", "RSS", "JSON"]

